AWSTemplateFormatVersion: 2010-09-09
Description: RDS PostgreSQL Instance

Parameters:
  VpcId:
    Type: String
  Username:
    Type: String
    Default: postgres
  Password:
    Type: String
    NoEcho: true
    Description: The database master password
  BackupRetentionPeriod:
    Type: Number
    Default: 0
  InstanceClass:
    Type: String
    Default: db.t3.micro
  Engine:
    Type: String
    Default: postgres
  EngineVersion:
    Type: String
    Default: 15.4
  PubliclyAccessible:
    Type: Boolean
    Default: true
  DeletionProtection:
    Type: Boolean
    Default: false
  RdsDatabaseName:
    Type: String
    Default: mydatabase
  RdsPort:
    Type: Number
    Default: 5432
  Subnets:
    Type: List<AWS::EC2::Subnet::Id>
    Description: A list of subnets for the DB subnet group

Resources:
  DbSg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for RDS Instance
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref RdsPort
          ToPort: !Ref RdsPort
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: My DB Subnet Group
      SubnetIds: !Ref Subnets

  RdsInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      DBInstanceIdentifier: !Sub "${AWS::StackName}-postgres"
      MasterUsername: !Ref Username
      MasterUserPassword: !Ref Password
      DBSubnetGroupName: !Ref DBSubnetGroup
      AllocatedStorage: 20
      AllowMajorVersionUpgrade: true
      AutoMinorVersionUpgrade: true
      Port: !Ref RdsPort
      EnableIAMDatabaseAuthentication: false
      BackupRetentionPeriod: !Ref BackupRetentionPeriod
      DBInstanceClass: !Ref InstanceClass
      DBName: !Ref RdsDatabaseName
      Engine: !Ref Engine
      DeletionProtection: !Ref DeletionProtection
      EngineVersion: !Ref EngineVersion
      PubliclyAccessible: !Ref PubliclyAccessible
      VPCSecurityGroups:
        - !GetAtt DbSg.GroupId

Outputs:
  StackName:
    Value: !Ref AWS::StackName

  RdsUsername:
    Value: !Ref Username
    Export:
      Name: !Sub ${AWS::StackName}RdsUsername

  RdsPort:
    Value: !Ref RdsPort
    Export:
      Name: !Sub ${AWS::StackName}RdsPort

  RdsDatabaseName:
    Value: !Ref RdsDatabaseName
    Export:
      Name: !Sub ${AWS::StackName}RdsDatabaseName

  RdsEndpoint:
    Value: !GetAtt RdsInstance.Endpoint.Address
    Export:
      Name: !Sub ${AWS::StackName}RdsEndpoint
