AWSTemplateFormatVersion: '2010-09-09'
Description: Launch EC2 instance with Security Group in specified VPC and Subnet

Resources:
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH and HTTP access
      VpcId: vpc-091a5b44e6bc0a38d
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: 0
          ToPort: 0
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: MySecurityGroup

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-097947612b141c026  # Double-check this — AMI IDs usually start with "ami-"
      SubnetId: subnet-0b3394be48fef9872
      SecurityGroupIds:
        - !Ref MySecurityGroup
      Tags:
        - Key: Name
          Value: MyEC2Instance

Outputs:
  SecurityGroupId:
    Description: The ID of the created Security Group
    Value: !Ref MySecurityGroup

  InstanceId:
    Description: The ID of the created EC2 instance
    Value: !Ref MyEC2Instance
